### ISSUE TITLE
Disable some days

### ISSUE THREAD

**Issue by ciuadri** [BrockReece/vue-fullcalendar-example#13]
Hi,

It's possible to disable some days like weekends?

**Comment by BrockReece** [comment]
Depending on your needs, FullCalendar will allow you to hide [weekends](https://fullcalendar.io/docs/weekends)
```js
config: {
  weekends: false
}
```

Though if you need more flexibility, Fullcalendar also has a config option for [hiding days]( https://fullcalendar.io/docs/hiddenDays) 

The following also hides the weekends 
```js
config: {
  hiddenDays: [ 6, 7 ]
}
```

**Comment by ciuadri** [comment]
Thanks man!

**Comment by BrockReece** [comment]
No probs
