### ISSUE TITLE
Probably a config issue but getting:  Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by adavie1** [BrockReece/vue-fullcalendar-example#2]
Hi,
My set up code is like this (in main.js):

`Vue.use(require('vue-full-calendar'))`

The usage, (in another component) is like this:

**HTML Section**:
```
<vue-full-calendar :events="selEvents" @eventClick="eventSelected">
</vue-full-calendar>

```
**Script Section**:
```
...
import VueFullCalendar from 'vue-full-calendar'

export default {
  components: {
    GeneralAction,
    VueFullCalendar
  },
...

```

BTW I've included the CSS import in App.vue - the main entry point.

Any pointers as to what I'm doing wrong would be great! :-)

**Comment by BrockReece** [comment]
Hi @adavie1, 

Look at my usage in [this example](https://github.com/BrockReece/vue-fullcalendar-example/blob/master/src/App.vue)

Give me a shout if you need further help.

Cheers
Brock

**Comment by adavie1** [comment]
Hi Brock, thanks for the reply. I'm clearly doing something silly- 

I've copied your code as given, get "undefined component" error. I'm using Vue 2.3.6.

To fixe this, I tried this:

```
import FullCalendar from 'vue-full-calendar'
...
components: {
  FullCalendar
}
...

```
Then I get the same error as before.

I'm doing exactly what I've done for other components. Whilst I'm relatively new to Vue, I've been working with it very intensely for a few months, however, this is the first time I've used a jQuery wrapper component.

I've tried with the window.jQuery ... line and without. No change in behaviour.

Thanks again for your time.
Anthony

**Comment by adavie1** [comment]
Hi Brock,
I've added the following lines to `main.js` and it now works, however, they are not in the example code.

```
window.jQuery = window.$ = require('jquery')
Vue.use(require('vue-full-calendar'))

```
I'm still slightly confused as to how it works, since the `Vue.use` reference is to `vue-full-calendar`, yet the component is referenced as `<full-calendar>`. Not seen this behaviour in Vue before.

**Comment by BrockReece** [comment]
Hi @adavie1,
Glad you have it working.

So this magic is happening in the plugin, basically, it globally registers a component in Vue with the following command.
```js
Vue.component('full-calendar', require('./fullcalendar.vue'))
```
The first argument is the name of the component that you reference in your template.

If you are using webpack, you can load jQuery inside your config, as I am [here](https://github.com/BrockReece/vue-fullcalendar-example/blob/master/build/webpack.base.conf.js#L22)

Hope this helps.

Cheers
Brock

**Comment by adavie1** [comment]
Right, got it. Thanks Brock.

So it's not necessry to use the format:

`import FullCalendar from 'vue-full-calendar'`

This pattern is slightly different form the other import patterns for all other components. No issues with that, just observing.

Thanks for the webpack snippet, which I am using. i'll incorporate that into my config file.
