### ISSUE TITLE
Example don't work

### ISSUE THREAD

**Issue by zoat** [BrockReece/vue-fullcalendar-example#3]
I try  your  example  but  it  not work , I have node  v6.11.3 and  3.10.10  . I have  this  stakTrace 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle calendar-example@1.0.0~predev: calendar-example@1.0.0
6 silly lifecycle calendar-example@1.0.0~predev: no script for predev, continuing
7 info lifecycle calendar-example@1.0.0~dev: calendar-example@1.0.0
8 verbose lifecycle calendar-example@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle calendar-example@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\vuproject\vue-fullcalendar-example\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.8.0_144\bin;C:\Program Files\Git\cmd;C:\Program 
10 verbose lifecycle calendar-example@1.0.0~dev: CWD: C:\Users\vuproject\vue-fullcalendar-example
11 silly lifecycle calendar-example@1.0.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle calendar-example@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle calendar-example@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: calendar-example@1.0.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid calendar-example@1.0.0
16 verbose cwd C:\vue-fullcalendar-example
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.11.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error calendar-example@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the calendar-example@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the calendar-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs calendar-example
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls calendar-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

THanks

**Comment by BrockReece** [comment]
I presume that you ran `npm install` or `yarn` before trying to run the dev server?

Is there anything in your npm-debug.log?

**Comment by zoat** [comment]
Yes,  I  ran  npm install   before npm run dev.
and this is my npm-debug.log

 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle calendar-example@1.0.0~predev: calendar-example@1.0.0
6 silly lifecycle calendar-example@1.0.0~predev: no script for predev, continuing
7 info lifecycle calendar-example@1.0.0~dev: calendar-example@1.0.0
8 verbose lifecycle calendar-example@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle calendar-example@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\\vuproject\vue-fullcalendar-example\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.8.0_144\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\\AppData\Local\Microsoft\WindowsApps;C:\Users\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin
10 verbose lifecycle calendar-example@1.0.0~dev: CWD: C:\Users\vuproject\vue-fullcalendar-example
11 silly lifecycle calendar-example@1.0.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle calendar-example@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle calendar-example@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: calendar-example@1.0.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid calendar-example@1.0.0
16 verbose cwd C:\Users\vuproject\vue-fullcalendar-example
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.11.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error calendar-example@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the calendar-example@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the calendar-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs calendar-example
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls calendar-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by BrockReece** [comment]
I'm really sorry but I can't replicate the issue. I use a Mac though and don't have access to a Windows machine at the moment.

Can any other Windows users confirm this error?
