### ISSUE TITLE
Weird bug with firstDay option and vuex store

### ISSUE THREAD

**Issue by smingam** [BrockReece/vue-fullcalendar-example#4]
Hi!

I encountered a super weird bug using the [firstDay option](https://fullcalendar.io/docs/display/firstDay/) and a vuex store.
In that bit of code in fullcalendar.js @ 11754:
```javascript
if (firstDay != null) {
	_week = createObject(localeData._week); // _week: { dow: # }
	_week.dow = firstDay;
	localeData._week = _week;
}
```
fullCalendar try to create an object from a locale object and this object appears to be a moment.localeData()
```javascript
// Returns moment's internal locale data. If doesn't exist, returns English.
function getMomentLocaleData(localeCode) {
	return moment.localeData(localeCode) || moment.localeData('en');
}
```
 For some reason that I would like to understand, that object come with some reactiveSetter from vuex, hence a warning of mutating it outside a mutation? I'm at a complete loss of what's happening, so I created an example here:
https://github.com/smingam/vue-fullcalendar-example/tree/bug-firstDay-vuex

I can live without that firstDay option, but I think great javascript wisdom can come from that bug, so any help or explanation would be greatly appreciated!

Cheers

**Comment by BrockReece** [comment]
Hey, so off the top off my head, I am guessing it is because moment objects aren't immutable.
I could suggest trying to map through the events in the store's getter and use moment's `clone` method on the start and end dates.  

```js
// getters
const getters = {
    events: (state) => state.events.map(event => ({
        ...event,
        start: event.start.clone(),
        end: event.end.clone(),
    })),
}
```

**Comment by smingam** [comment]
Hi!
Thanks a lot for your support and sorry for the late answer, the project I'm using your plugin on didn't leave me much time to reply!
Anyway, has I was getting more and more pissed with those vuex issues and performances (caused mainly by the strict mode of my dev version btw), I moved the calendar to eventSources, which gave me great refresh performance and no need to externally tracks date and week to make the api calls.
So thank you to have looked on my issue, and thanks again for your great plugin!

Cheers

**Comment by BrockReece** [comment]
No problem, thanks for the kind words.
